FROM node:18-buster

USER root

WORKDIR /home/node/app

RUN npm install --include=optional -g @nestjs/cli

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate dev && npx prisma db seed && npm run start:dev"]
