services:
  postgres:
    image: postgres:15-bullseye
    container_name: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=789523146
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_db

  backend:
    container_name: backend
    volumes:
      - ./:/home/node/app
    restart: always
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - postgres